Repository DSC-ASEB/Getting-started-with-Hacktoberfest, pull requests merged in 2020-10, with the labels that each got.

#5 Bubble Sort
  Python/bubble_sort.py
Labels: Hacktoberfest

#6 Merge sort
  Python/merge_sort.py
Labels: Hacktoberfest

#15 DiamondPattern.java
  Java/DiamondPattern.java
Labels: Hacktoberfest, Java

#8 Added Time format Converter
  Python/time_format_converter.py
Labels: Hacktoberfest, Python, size/S

#20 Create String Formatting.py - HackerRank problem
  Python/Decimal, Octal, Hexadecimal and Binary.py
Labels: Hacktoberfest, size/S

#22 added half pyramid for >=5
  Python/even_pattern.py
  Python/half_pyramid_pattern.py
Labels: Hacktoberfest, size/S

#23 Addede a new Feature
  Python/half_pyramid_numbers.py
  Python/half_pyramid_reverse_numbers.py
Labels: Hacktoberfest, size/S

#24 new feature added
  Python/Disp1to10pattern.py
Labels: Hacktoberfest, size/XS

#25 Create Revdisp.py
  Python/reverse_display_numbers_half_pyramid.py
Labels: size/S

#11 decimaltoocta decimal,factoral ,fibonacci,heap sort
  C/circularQueue.c
  C/heapsort.c
  C/stack.c
  Screenshot (25).png
  Screenshot (26).png
Labels: C, Hacktoberfest, size/L
